#ifndef VISIONAPPSTRUCT_H
#define VISIONAPPSTRUCT_H

enum RecipeSettingsMenuButton
{
	NEWRECIPE = 0,
	LOADRECIPE = 1,
	SAVERECIPE = 2,
	DUPLICATERECIPE = 3,
	ARCHIVERECIPE = 4,
	RESTORERECIPE = 5,
	SHOWRECIPEINEXPLORER = 6,
	PATHEDITOR = 7
};

enum SystemSettingsMenuButton
{
	CONFIG = 0,
	SCALING = 1,
	LIGHTING = 2,
	ANALYSIS = 3,
	TESTRUN = 4,
	LASER = 5,
	PORTABILITY = 6,
	AIMODEL = 7,
	ZSTACK = 8,
	OPTICS3D = 9,
	BARCODEREADER = 10,
	ALGOSETUP = 11
};

#endif // VISIONAPPSTRUCT_H
